import Head from "next/head";
import Hero from "../components/Hero";
import Menu from "../components/Menu";
import Services from "../components/Services";
import { client } from "../lib/client";
import styles from "../styles/Home.module.css";

export default function Home({ pizzas }) {
  return (
      <div className={styles.container}>
        <Head>
          <title>FUDO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        <Hero />
        <Services />
        <Menu pizzas={pizzas} />

        {/* body 
        <main>
          <h1>Subscribe Zainkeepscode</h1>        
        </main>*/}
      </div>
  );
}

export const getServerSideProps =  async() => {
  const query = "*[_type == 'pizza']";
  const pizzas = await client.fetch(query);
  return {
    props: {
      pizzas
    }
  }
}